## Research Notebook for PISA question and answers on different languages

## Libraries

In [1]:
import os, getpass

In [2]:
from dotenv import load_dotenv, find_dotenv

In [3]:
from openai import OpenAI

In [4]:
load_dotenv(find_dotenv(usecwd=True))  # finds .env from current working dir upward

True

In [5]:
# --- 0) Setup: imports & config
import os, re, time, json, math, random
from typing import Dict, List, Tuple, Any, Optional
import pandas as pd
import time

In [6]:
from tqdm import tqdm

## Configuration

In [7]:
client = OpenAI()

In [8]:
MODEL_GPT = "gpt-5.1-2025-11-13"                    # <- replace with exact model id if different
# gpt-5-2025-08-07
# gpt-5.1-2025-11-13
# gpt-5.2-2025-12-11

In [9]:
SHEET_ID = "1QVPzB7uMwqJ6jCsHkwIILnXvDQIycpqkcV3bkiDpzyQ" 
WORKSHEET_NAME = "dataset"  # change if needed "dataset"
RESULTS_CSV = "llm_eval_results_GPT5.csv"
SAMPLE_PER_LANGUAGE = 1     # 5 per language
MAX_LANGUAGES = 43          # 43 languages total
SEED = 42

random.seed(SEED)

## Load data from Google Sheet

In [10]:
csv_url = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/gviz/tq?tqx=out:csv&sheet={WORKSHEET_NAME}"
try:
    df = pd.read_csv(csv_url)
except Exception as e:
    raise RuntimeError(
        "Failed to read the Google Sheet via CSV export. "
        "Make sure the sheet is shared as 'Anyone with the link can view', "
        f"ID is correct, and tab name matches. Underlying error: {e}"
    )

expected_cols = {
    "qid","language","question","context","options","gold",
    "answer_type","category","difficulty","rationale","source"
}
missing = expected_cols - set(df.columns)
if missing:
    raise ValueError(f"Your sheet is missing columns: {sorted(missing)}")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1075 entries, 0 to 1074
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qid            1075 non-null   object
 1   language       1075 non-null   object
 2   language_code  1075 non-null   object
 3   question       1075 non-null   object
 4   context        1075 non-null   object
 5   options        1075 non-null   object
 6   gold           1075 non-null   object
 7   answer_type    1075 non-null   object
 8   category       1075 non-null   object
 9   difficulty     1075 non-null   object
 10  rationale      172 non-null    object
 11  source         1075 non-null   object
dtypes: object(12)
memory usage: 100.9+ KB

## Normalize & sample

In [12]:
df["language"] = df["language"].astype(str).str.strip()
# pick first MAX_LANGUAGES languages (sorted)
languages = sorted(df["language"].unique())[:MAX_LANGUAGES]

In [13]:
# sample up to SAMPLE_PER_LANGUAGE per language
sampled = (
    df[df["language"].isin(languages)]
    .groupby("language", sort=True, group_keys=False)
    .head(SAMPLE_PER_LANGUAGE)
    .reset_index(drop=True)
)
if sampled.empty:
    raise ValueError("No rows selected. Check your data.")

In [14]:
print(f"Selected {len(sampled)} rows across {sampled['language'].nunique()} languages.")
display(sampled[["qid","language","question","gold"]])

Selected 43 rows across 43 languages.

,qid,language,question,gold
0,q001,Albanian,Nëse Tania vendos të blejë makinën D dhe ta sh...,C
1,q001,Arabic,إذا قررت تهاني شراء السيارة D وإعادة بيعها بع...,C
2,q001,Azerbaijani / Azeri,Əgər Turan maşın D-ni almağa və üç il sonra əl...,C
3,q001,Basque,Taniak erabakitzen badu D autoa erostea eta ho...,C
4,q001,Bokmål,Omtrent hvor mye vil bruktprisen av bilen være...,C
5,q001,Bosnian,"Ako Tanja odluči da kupi automobil D, i prepro...",C
6,q001,Bulgarian,Ако Таня реши да купи кола Г и я препродаде сл...,C
7,q001,Catalan,Si la Tània decideix comprar el cotxe D i reve...,C
8,q001,Chinese,如果田妮决定购买汽车 D 并于三年后在良好车况下转售，那么这辆汽车的转售价格大约是多少 (z...,C
9,q001,Croatian,Ako Tanja odluči kupiti automobil D i preproda...,C
10,q001,Czech,Jaká bude přibližná prodejní cena auta (v zede...,C
11,q001,Danish,Hvis Tanja beslutter at købe bil D og videresæ...,C
12,q001,Dutch,Als Tanja besluit om auto D te kopen en deze n...,C
13,q001,English,If Tania decides to buy car D and resell it af...,C
14,q001,Estonian,Kui Tanja otsustab osta auto D ja müüa selle k...,C
15,q001,Finnish,Jos Tanja päättäisi ostaa auton D ja myydä sen...,C
16,q001,French,Si Tania décide d'acheter la voiture D et de l...,C
17,q001,Galician,Se Tania decide mercar o coche D e revendelo d...,C
18,q001,Georgian,"თუ ქეთი გადაწყვეტს, იყიდოს მანქანა D და გაყიდო...",C
19,q001,German,"Wenn sich Tanja entscheidet, Auto D zu kaufen ...",C
20,q001,Greek,Εάν η Τάνια αποφασίσει να αγοράσει το αυτοκίνη...,C
21,q001,Hebrew,אם טליה תחליט לקנות את מכונית ד ולמכור אותה במ...,C
22,q001,Hungarian,"Ha Tímea a D autó megvásárlása mellett dönt, m...",C
23,q001,Icelandic,Ef Tanja ákveður að kaupa bíl D og selja hann ...,C
24,q001,Indonesian,Jika Tania memutuskan untuk membeli mobil D da...,C
25,q001,Italian,Se Tania decidesse di comprare l'automobile D ...,C
26,q001,Japanese,もし千夏さんが自動車Dを買うと決めて、3年後にそれを大変良い状態で売ることができるとしたら、...,C
27,q001,Kazakh,Егер Тоғжан Г автокөлігін сатып алуды шешіп жә...,C
28,q001,Korean,"태연이가 자동차 D를 구입하여 3년 후에 최상의 상태로 되판다면, 자동차의 중고차 ...",C
29,q001,Latvian,Kāda būs mašīnas aptuvenā tālākpārdošanas cena...,C
30,q001,Lithuanian,Jeigu Tania nuspręstų įsigyti D automobilį ir ...,C
31,q001,Malay,Sekiranya Tania membuat keputusan untuk membel...,C
32,q001,Nynorsk,Omtrent kor høg vil bruktprisen for bilen vere...,C
33,q001,Polish,Jeśli Teresa postanowi kupić samochód D i odsp...,C
34,q001,Portuguese,Se a Tânia decidir comprar o carro D e o vende...,C
35,q001,Russian,Если Таня решит купить машину Г и перепродать ...,C
36,q001,Serbian / Serb,"Ako Tanja odluči da kupi automobil D, i prepro...",C
37,q001,Slovak,"Ak sa Táňa rozhodne, že si kúpi auto D a po tr...",C
38,q001,Slovenian,Če se bo Tanja odločila za nakup avtomobila D ...,C
39,q001,Spanish,Si Tania decidiese comprar el coche D y revend...,C
40,q001,Swedish,Om Tanja bestämmer sig för att köpa Bil D och ...,C
41,q001,Thai,ถ้าทิชาตัดสินใจซื้อรถยนต์ D และขายรถยนต์คันนี้...,C
42,q001,Turkish,"Tuğçe, Araba D'yi almaya ve üç yıl sonra satma...",C

## Parse options

In [15]:
def parse_options(raw: str) -> Dict[str, Any]:
    """
    Parse multiple-choice options from a JSON-encoded string.

    Supported formats
    -----------------
    1) Simple labeled strings (original format):
        ["A) 1575", "B) 8925", "C) 9000", "D) 9975"]

        -> {"A": "1575", "B": "8925", "C": "9000", "D": "9975"}

    2) List of dicts with labels mapping to lists of tokens:
        [
          {"A": ["India", "Colombia"]},
          {"B": ["India", "Armenia"]},
          {"C": ["Panama", "Colombia"]},
          {"D": ["Kazakhstan", "Colombia"]}
        ]
    """
    if pd.isna(raw):
        raise ValueError("Options are empty")

    # Load JSON
    try:
        items = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON format for options: {e}")

    if not isinstance(items, list):
        raise ValueError("Expected a JSON list at top level")

    # Case 1: list of strings -> original behavior
    if all(isinstance(item, str) for item in items):
        options: Dict[str, Any] = {}
        for item in items:
            # Match patterns like "A) text", "B. text", or "C: text"
            if not isinstance(item, str):
                raise ValueError(f"Option is not a string: {item}")
            match = re.match(r"^\s*([A-Z])[\)\.\:]\s*(.+)$", item.strip())
            if match:
                label, text = match.groups()
                options[label.upper()] = text.strip()
            else:
                # Fallback: assign next available letter automatically
                next_label = chr(ord('A') + len(options))
                options[next_label] = item.strip()
        return options

    # Case 2: list of dicts like [{"A": [...]}, {"B": [...]}]
    if all(isinstance(item, dict) for item in items):
        options: Dict[str, Any] = {}
        for idx, d in enumerate(items):
            if len(d) != 1:
                raise ValueError(
                    f"Each dict must have exactly one key (label). Problem at index {idx}: {d}"
                )
            (label_raw, value) = next(iter(d.items()))
            if not isinstance(label_raw, str):
                raise ValueError(f"Label must be a string, got: {label_raw}")

            label = label_raw.strip().upper()
            if not re.fullmatch(r"[A-Z]", label):
                raise ValueError(f"Invalid option label '{label_raw}' at index {idx}")

            # Accept list or scalar; normalize scalars into single-element lists if needed
            if isinstance(value, list):
                options[label] = value
            else:
                options[label] = [value]

        return options

    # If we reach here, the list is mixed or has unsupported types
    raise ValueError(
        "Unsupported options format: expected list of strings or list of single-key dicts"
    )

In [16]:
test = parse_options('["A) 2018", "B) 2019", "C) 2020", "D) 2021"]')
print(test)

{'A': '2018', 'B': '2019', 'C': '2020', 'D': '2021'}

In [17]:
options_block = "\n".join([f"{k}. {v}" for k,v in test.items()])
print(options_block)

A. 2018
B. 2019
C. 2020
D. 2021

## Build prompt

In [18]:
def build_prompt(row: pd.Series, options: Dict[str,str]) -> str:
    """
    Builds prompt for MCQ.
    """
    options_block = "\n".join([f"{k}. {v}" for k,v in options.items()])

    return (
        f"{row['context']}\n"
        f"{row['question']}\n"
        f"{options_block}\n\n"
    )

In [19]:
answer_letter_regex = re.compile(r"<\s*([A-Z])\s*[.)]?\s*>")

def extract_letter(text: str, valid_letters: List[str]) -> str:
    """
    Extract the first single-letter A-Z token that is in valid_letters.
    """
    if not text:
        return ""
    # First line is the letter per our format; but still be defensive:
    first_line = text.splitlines()[0].strip().rstrip(".)").upper()
    # If first line is a single valid letter, use it
    if len(first_line) == 1 and first_line.upper() in valid_letters:
        return first_line.upper()
    # Else find any A-Z token
    m = answer_letter_regex.search(text.upper())
    if m and m.group(1) in valid_letters:
        return m.group(1)
    return ""

## LLM call wrapper

In [20]:
def llm_completion(
    prompt: str,
    model: Optional[str] = None,
    max_tokens: Optional[int] = None,
    system_prompt: str="Reply format: <LETTER>", #"", #
    retries: int = 2,
    backoff_seconds: float = 1.5,
    reasoning_effort: Optional[str] = None,     # e.g., "low"|"medium"|"high" (and some models support "none")
    reasoning_summary: Optional[str] = None,    # e.g., "auto" (or "concise"/"detailed" depending on model)
    **kwargs,
) -> Tuple[str, Dict[str, Any]]:
    """
    Call OpenAI Responses API and return (text, usage_dict).
    usage_dict contains: input_tokens, output_tokens, total_tokens (if present)
    """
    mdl = model or MODEL_GPT
    last_err = None

    for attempt in range(retries + 1):
        try:
            # Build arguments dynamically — include only if provided
            call_args = dict(
                model=mdl,
                instructions=system_prompt,
                input= prompt,
                stream=False
            )

            # ---- attach token limits if provided ----
            if max_tokens is not None:
                call_args["max_tokens"] = max_tokens

            # ---- NEW: reasoning controls ---- :contentReference[oaicite:4]{index=4}
            if reasoning_effort is not None or reasoning_summary is not None:
                r = {}
                if reasoning_effort is not None:
                    r["effort"] = reasoning_effort
                if reasoning_summary is not None:
                    r["summary"] = reasoning_summary
                call_args["reasoning"] = r

            # Merge other kwargs (e.g., stop, seed, etc.)
            for k, v in kwargs.items():
                if k not in call_args:
                    call_args[k] = v

            # Actual model call
            response = client.responses.create(**call_args)
            if response is None:
                return "No response from model.", {}
            
            text = (getattr(response, "output_text", "") or "").strip()

            # --- Extract usage safely across SDK versions ---
            usage_obj = getattr(response, "usage", None)

            def _get(obj, key, default=None):
                if obj is None:
                    return default
                if isinstance(obj, dict):
                    return obj.get(key, default)
                return getattr(obj, key, default)

            usage: Dict[str, Any] = {
                "input_tokens": None,
                "output_tokens": None,
                "reasoning_tokens": None,
                "effort": reasoning_effort,
                "summary": "",
            }

            if usage_obj is not None:
                # SDK objects often allow attribute access; dict-like in some contexts.
                
                usage["input_tokens"] = _get(usage_obj, "input_tokens")
                usage["output_tokens"] = _get(usage_obj, "output_tokens")

                out_details = _get(usage_obj, "output_tokens_details", {})
                usage["reasoning_tokens"] = _get(out_details, "reasoning_tokens")    

            if reasoning_summary is not None:
                try:
                    out_items = getattr(response, "output", None) or []
                    for item in out_items:
                        item_type = _get(item, "type")
                        if item_type == "reasoning":
                            summaries = _get(item, "summary", []) or []
                            parts = []
                            for s in summaries:
                                if _get(s, "type") == "summary_text":
                                    parts.append(_get(s, "text", "") or "")
                            usage["summary"] = "\n\n".join([p for p in parts if p]).strip()
                            break
                except Exception:
                    # keep meta["summary"] as empty if shape differs
                    pass            

            return text, usage

        except Exception as e:
            last_err = e
            if attempt < retries:
                time.sleep(backoff_seconds * (attempt + 1))
            else:
                raise

## Evaluation loop

In [51]:
def eval_rows(
        rows: pd.DataFrame, 
        cycle: int,
        model_tag: str,
        model_name: str, 
        results_path: str = RESULTS_CSV,
        sleep_s: float = 0.0, 
        retries: int = 2
    ) -> pd.DataFrame:
    results = []
    file_exists = os.path.exists(results_path)
    for i, row in tqdm(rows.iterrows(), total=len(rows), desc=f"Evaluating {model_tag} / {model_name}, cycle {cycle}"):
        qid = row["qid"]
        lang = row["language"]
        gold = str(row["gold"]).strip().upper()
        difficulty = row["difficulty"]

        # Parse options
        try:
            opts = parse_options(row["options"])
        except Exception as e:
            row_result = {
                "qid": qid,
                "language": lang,
                "pred": "",
                "gold": gold,
                "is_correct": False,
                "error": f"OptionsParseError: {e}",
                "raw": "",
                "difficulty": difficulty,
                "question": row["question"],
                "options_json": json.dumps(opts if 'opts' in locals() else {}, ensure_ascii=False),
                "model_tag": model_tag,
                "model_name": model_name,
                "cycle": cycle,
                "input_tokens": 0,
                "output_tokens": 0,
                "reasoning_tokens": 0,
                "effort": "Default",
                "summary": "",
            }
            results.append(row_result)

            # Save immediately
            pd.DataFrame([row_result]).to_csv(
                results_path,
                mode="a",
                header=not file_exists,
                index=False,
                encoding="utf-8"
            )
            file_exists = True
            continue

        valid_letters = sorted(list(opts.keys()))
        prompt = build_prompt(row, opts)

        # call model with simple retry
        raw = ""
        usage = {}
        err = ""
        for attempt in range(retries + 1):
            try:
                raw, usage = llm_completion(
                    prompt,
                    model=model_name,
                    reasoning_effort="none",     # <-- Optional. choose per run / per model
                    reasoning_summary="auto",   # <-- Optional. or None to disable summaries
                )
                break
            except Exception as e:
                err = f"{type(e).__name__}: {e}"
                if attempt < retries:
                    time.sleep(1.5 * (attempt + 1))
                else:
                    raw, usage = "", {}
        pred = extract_letter(raw, valid_letters)
        is_correct = (pred == gold)

        row_result = {
            "qid": qid,
            "language": lang,
            "pred": pred,
            "gold": gold,
            "is_correct": bool(is_correct),
            "error": err,
            "raw": raw,
            "difficulty": difficulty,
            "question": row["question"],
            "options_json": json.dumps(opts, ensure_ascii=False),
            "model_tag": model_tag,
            "model_name": model_name,
            "cycle": cycle,
            "input_tokens": usage.get("input_tokens"),
            "output_tokens": usage.get("output_tokens"),
            "reasoning_tokens": usage.get("reasoning_tokens"),
            "effort": usage.get("effort"),
            "summary": usage.get("summary", ""),
        }

        results.append(row_result)

        # *** Save this row immediately ***
        pd.DataFrame([row_result]).to_csv(
            results_path,
            mode="a",
            header=not file_exists,
            index=False,
            encoding="utf-8"
        )
        file_exists = True

        if sleep_s > 0:
            time.sleep(sleep_s)
    return pd.DataFrame(results)

## Execution

In [52]:
MODELS_TO_TEST = [
    ("GPT", MODEL_GPT)
]

In [53]:
# filtered_df = df[df["language"] == "English"]
sampled = df

In [65]:
N_CYCLES = 5  # repeat the same question to the same LLM

In [ ]:
if os.path.exists(RESULTS_CSV):
    existing_results = pd.read_csv(RESULTS_CSV)
    print(f"Loaded existing results from {RESULTS_CSV}: {len(existing_results)} rows")
else:
    existing_results = pd.DataFrame()
    print("No existing results file found. Starting fresh.")

for tag, model_name in MODELS_TO_TEST:
    print(f"\nEvaluating {tag} -> {model_name}")
    for cycle in range(2, N_CYCLES + 1):
        # Determine which qids are already done for this (tag, model_name, cycle)
        if existing_results.empty:
            # Nothing done yet at all
            rows_to_eval = sampled.copy()
        else:
            # Subset only rows already done for this (tag, model_name, cycle)
            subset = existing_results[
                (existing_results["model_tag"] == tag) &
                (existing_results["model_name"] == model_name) &
                (existing_results["cycle"] == cycle)
            ]

            if subset.empty:
                # No rows done yet for this model+cycle
                rows_to_eval = sampled.copy()
            else:
                # Use (qid, language) pairs as the key — more robust than qid alone
                done_pairs = set(zip(subset["qid"], subset["language"]))

                mask = ~sampled.apply(
                    lambda r: (r["qid"], r["language"]) in done_pairs,
                    axis=1
                )
                rows_to_eval = sampled[mask]

        if rows_to_eval.empty:
            print(f"  • cycle {cycle}/{N_CYCLES}: already complete, skipping")
            continue

        print(f"  • cycle {cycle}/{N_CYCLES}: evaluating {len(rows_to_eval)} questions")
        t0 = time.time()

        df_new = eval_rows(
            rows_to_eval,
            model_tag=tag,
            model_name=model_name,
            cycle=cycle,
            results_path=RESULTS_CSV
        )

        elapsed = time.time() - t0
        print(f"    Done in {elapsed:.1f}s, newly evaluated {len(df_new)} rows.")

        # Update in-memory copy so subsequent cycles/ models can see freshly written rows
        existing_results = pd.concat([existing_results, df_new], ignore_index=True)

Loaded existing results from llm_eval_results_GPT5.csv: 3225 rows

Evaluating GPT -> gpt-5.1-2025-11-13
  • cycle 5/5: evaluating 1075 questions

Evaluating GPT / gpt-5.1-2025-11-13, cycle 5: 100%|██████████| 1075/1075 [16:12<00:00,  1.11it/s]

    Done in 972.6s, newly evaluated 1075 rows.

In [67]:
res_df = pd.read_csv(RESULTS_CSV)
print(f"\nTotal results loaded: {len(res_df)}")

Total results loaded: 4300

## Results

In [68]:
overall_by_model = (
    res_df.groupby(["model_tag","model_name"])["is_correct"]
    .mean()
    .reset_index()
    .rename(columns={"is_correct":"accuracy"})
    .sort_values("accuracy", ascending=False)
)
print("\nOverall accuracy by model:")
display(overall_by_model)

Overall accuracy by model:

  model_tag          model_name  accuracy
0       GPT  gpt-5.1-2025-11-13  0.786744

In [69]:
overall_by_question = (
    res_df.groupby(["qid"])["is_correct"]
    .mean()
    .reset_index()
    .rename(columns={"is_correct":"accuracy"})
    .sort_values("accuracy", ascending=False)
)
print("\nOverall accuracy by question:")
display(overall_by_question)

Overall accuracy by question:

     qid  accuracy
4   q005  1.000000
8   q009  1.000000
5   q006  1.000000
24  q025  1.000000
21  q022  1.000000
20  q021  1.000000
19  q020  1.000000
16  q017  1.000000
15  q016  1.000000
23  q024  0.976744
2   q003  0.976744
12  q013  0.976744
13  q014  0.976744
10  q011  0.965116
6   q007  0.959302
11  q012  0.924419
22  q023  0.918605
7   q008  0.906977
14  q015  0.901163
3   q004  0.540698
1   q002  0.244186
17  q018  0.186047
18  q019  0.156977
9   q010  0.058140
0   q001  0.000000

In [70]:
overall_by_lang = (
    res_df.groupby(["language"])["is_correct"]
    .mean()
    .reset_index()
    .rename(columns={"is_correct":"accuracy"})
    .sort_values("accuracy", ascending=False)
)
print("\nOverall accuracy by lang:")
display(overall_by_lang)

Overall accuracy by lang:

               language  accuracy
6             Bulgarian      0.85
41                 Thai      0.85
22            Hungarian      0.85
35              Russian      0.85
12                Dutch      0.84
15              Finnish      0.83
34           Portuguese      0.82
11               Danish      0.82
19               German      0.82
3                Basque      0.81
1                Arabic      0.81
32              Nynorsk      0.81
18             Georgian      0.81
39              Spanish      0.81
40              Swedish      0.81
38            Slovenian      0.80
30           Lithuanian      0.80
0              Albanian      0.80
10                Czech      0.80
16               French      0.80
42              Turkish      0.80
20                Greek      0.79
31                Malay      0.79
26             Japanese      0.79
7               Catalan      0.79
9              Croatian      0.78
36       Serbian / Serb      0.78
33               Polish      0.78
29              Latvian      0.77
2   Azerbaijani / Azeri      0.77
4                Bokmål      0.76
24           Indonesian      0.76
13              English      0.76
14             Estonian      0.75
5               Bosnian      0.75
25              Italian      0.75
27               Kazakh      0.75
17             Galician      0.74
8               Chinese      0.73
37               Slovak      0.73
21               Hebrew      0.73
23            Icelandic      0.72
28               Korean      0.67

In [71]:
by_question = (
    res_df.groupby(["model_tag","model_name","language","qid"])["is_correct"]
    .mean()
    .reset_index()
    .rename(columns={"is_correct":"accuracy"})
    .sort_values(["accuracy"])
)

# print("\nAccuracy by question:")
# display(by_question)

accuracy_counts_total = (
    by_question["accuracy"]
    .value_counts()
    .rename_axis("accuracy")
    .reset_index(name="count")
    .sort_values("accuracy")
)

print("\nCount of total questions by accuracy:")
display(accuracy_counts_total)

accuracy_counts = (
    by_question
    .groupby(["model_tag", "model_name", "accuracy"], as_index=False)
    .size()
    .rename(columns={"size": "count"})
    .sort_values(["model_tag", "model_name", "accuracy"])
)

print("\nCount of questions by accuracy:")
display(accuracy_counts)

Count of total questions by accuracy:

   accuracy  count
1      0.00    190
2      0.25     28
4      0.50     24
3      0.75     25
0      1.00    808

Count of questions by accuracy:

  model_tag          model_name  accuracy  count
0       GPT  gpt-5.1-2025-11-13      0.00    190
1       GPT  gpt-5.1-2025-11-13      0.25     28
2       GPT  gpt-5.1-2025-11-13      0.50     24
3       GPT  gpt-5.1-2025-11-13      0.75     25
4       GPT  gpt-5.1-2025-11-13      1.00    808

In [72]:
def safe_acc(s):
    return float('nan') if s.empty else s.mean()
overall_acc = safe_acc(res_df["is_correct"])
print(f"\nCombined overall accuracy on {len(res_df)} items: {overall_acc:.3f}")

Combined overall accuracy on 4300 items: 0.787

In [73]:
for tag, _ in MODELS_TO_TEST:
    out_path = f"llm_eval_results__{tag}.csv"
    res_df.query("model_tag == @tag").to_csv(out_path, index=False)
    print(f"Saved {tag} results to: {out_path}")

# (Optional) quick peek
display(res_df.head())

Saved GPT results to: llm_eval_results__GPT.csv

,qid,language,pred,gold,is_correct,error,raw,difficulty,question,options_json,model_tag,model_name,cycle,input_tokens,output_tokens,reasoning_tokens,effort,summary
0,q001,Albanian,B,C,False,NaN,B,level 6,Nëse Tania vendos të blejë makinën D dhe ta sh...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,198,11,0,none,NaN
1,q002,Albanian,B,C,False,NaN,B,level 6,"Nëse trendi i shitjeve vazhdon, në cilin vit n...","{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,126,11,0,none,NaN
2,q003,Albanian,B,B,True,NaN,B,level 2,Cili është numri më i madh i kutive mesatare q...,"{""A"": ""320"", ""B"": ""128"", ""C"": ""26"", ""D"": ""16""}",GPT,gpt-5.1-2025-11-13,2,224,11,0,none,NaN
3,q004,Albanian,C,C,True,NaN,C,level 6,Kompania e cila jep kamionë me qera konfirmoi ...,"{""A"": ""Ajo ka të drejtë, sepse lartësia e një ...",GPT,gpt-5.1-2025-11-13,2,540,11,0,none,NaN
4,q005,Albanian,D,D,True,NaN,D,level 2,"Mesatarisht, afërisisht sa milionë kilometra g...","{""A"": ""5 milionë km"", ""B"": ""30 milionë km"", ""C...",GPT,gpt-5.1-2025-11-13,2,171,11,0,none,NaN

In [74]:
df_false = res_df[res_df['is_correct'] == False]
display(df_false.head(50))

,qid,language,pred,gold,is_correct,error,raw,difficulty,question,options_json,model_tag,model_name,cycle,input_tokens,output_tokens,reasoning_tokens,effort,summary
0,q001,Albanian,B,C,False,NaN,B,level 6,Nëse Tania vendos të blejë makinën D dhe ta sh...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,198,11,0,none,NaN
1,q002,Albanian,B,C,False,NaN,B,level 6,"Nëse trendi i shitjeve vazhdon, në cilin vit n...","{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,126,11,0,none,NaN
9,q010,Albanian,C,A,False,NaN,C,level 6,Konsideroni dy periudhat kohore: 2005 deri në ...,"{""A"": [""India"", ""Kolumbia""], ""B"": [""India"", ""A...",GPT,gpt-5.1-2025-11-13,2,569,11,0,none,NaN
17,q018,Albanian,C,A,False,NaN,C,level 5,A është thënia fakt apo opinion?\nStudimet e f...,"{""A"": [""Opinion"", ""Fakt"", ""Fakt"", ""Opinion""], ...",GPT,gpt-5.1-2025-11-13,2,1630,11,0,none,NaN
18,q019,Albanian,C,A,False,NaN,C,level 3,A mund ta përfaqësojë kjo thënie qëllimin e ar...,"{""A"": [""Po"", ""Po"", ""Jo""], ""B"": [""Po"", ""Jo"", ""J...",GPT,gpt-5.1-2025-11-13,2,988,11,0,none,NaN
25,q001,Arabic,B,C,False,NaN,B,level 6,إذا قررت تهاني شراء السيارة D وإعادة بيعها بع...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,147,11,0,none,NaN
26,q002,Arabic,B,C,False,NaN,B,level 6,في حالة استمرار المبيعات في هذا الاتجاه، في أي...,"{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,129,11,0,none,NaN
34,q010,Arabic,C,A,False,NaN,C,level 6,بالنظر في الفترتين الزمنيتين: 2005 إلى 2010...,"{""A"": [""الهند"", ""كولومبيا ""], ""B"": [""الهند"", ""...",GPT,gpt-5.1-2025-11-13,2,537,11,0,none,NaN
42,q018,Arabic,C,A,False,NaN,C,level 5,هل تمثّل العبارة التالية حقيقة أم رأي؟\nتُعتبر...,"{""A"": [""رأي"", ""حقيقة"", ""حقيقة"", ""رأي""], ""B"": [...",GPT,gpt-5.1-2025-11-13,2,1359,11,0,none,NaN
43,q019,Arabic,C,A,False,NaN,C,level 3,هل يمكن أن تمثّل هذه الجملة الهدف من المقال؟\n...,"{""A"": [""نعم"", ""نعم"", ""لا""], ""B"": [""نعم"", ""لا"",...",GPT,gpt-5.1-2025-11-13,2,797,11,0,none,NaN
50,q001,Azerbaijani / Azeri,B,C,False,NaN,B,level 6,Əgər Turan maşın D-ni almağa və üç il sonra əl...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,184,11,0,none,NaN
51,q002,Azerbaijani / Azeri,B,C,False,NaN,B,level 6,"Əgər bu satış tendensiyası davam edərsə, yuxar...","{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,130,11,0,none,NaN
59,q010,Azerbaijani / Azeri,C,A,False,NaN,C,level 6,İki vaxt aralığını nəzərdən keçirin: 2005-2010...,"{""A"": [""Ölkə F"", ""Ölkə C""], ""B"": [""Ölkə F"", ""Ö...",GPT,gpt-5.1-2025-11-13,2,545,11,0,none,NaN
67,q018,Azerbaijani / Azeri,B,A,False,NaN,B,level 5,İfadə fakt yoxsa fikirdir?\nSüdün sağlamlıq üç...,"{""A"": [""Fikir"", ""Fakt"", ""Fakt"", ""Fikir""], ""B"":...",GPT,gpt-5.1-2025-11-13,2,1613,11,0,none,NaN
72,q023,Azerbaijani / Azeri,B,A,False,NaN,B,level 2,Məlumat İlahə_88-in probleminə uyğundurmu?\nNa...,"{""A"": [""Bəli"", ""Bəli"", ""Xeyr"", ""Xeyr"", ""Bəli""]...",GPT,gpt-5.1-2025-11-13,2,841,11,0,none,NaN
75,q001,Basque,B,C,False,NaN,B,level 6,Taniak erabakitzen badu D autoa erostea eta ho...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,184,11,0,none,NaN
76,q002,Basque,B,C,False,NaN,B,level 6,"Salmenten joera honek berdin jarraitzen badu, ...","{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,133,11,0,none,NaN
78,q004,Basque,B,C,False,NaN,B,level 6,Kamioiak alokatzen dituen enpresak adierazi du...,"{""A"": ""Arrazoi du, kutxa ertain baten altuera ...",GPT,gpt-5.1-2025-11-13,2,477,11,0,none,NaN
84,q010,Basque,C,A,False,NaN,C,level 6,Honako bi denbora-tarte hauek hartuko ditugu k...,"{""A"": [""India"", ""Kolonbia""], ""B"": [""India"", ""A...",GPT,gpt-5.1-2025-11-13,2,537,11,0,none,NaN
93,q019,Basque,C,A,False,NaN,C,level 3,Adierazpen honek adierazi al lezake artikuluar...,"{""A"": [""Bai"", ""Bai"", ""Ez""], ""B"": [""Bai"", ""Ez"",...",GPT,gpt-5.1-2025-11-13,2,893,11,0,none,NaN
100,q001,Bokmål,B,C,False,NaN,B,level 6,Omtrent hvor mye vil bruktprisen av bilen være...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,147,11,0,none,NaN
101,q002,Bokmål,B,C,False,NaN,B,level 6,"Hvis denne salgstrenden fortsetter, i hvilket ...","{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,107,11,0,none,NaN
103,q004,Bokmål,D,C,False,NaN,D,level 6,"Firmaet som leier ut flyttebilene, har bekreft...","{""A"": ""Hun har rett, fordi høyden til en eske ...",GPT,gpt-5.1-2025-11-13,2,438,11,0,none,NaN
109,q010,Bokmål,C,A,False,NaN,C,level 6,Vurder de to tidsperiodene: 2005 til 2010 og 2...,"{""A"": [""India"", ""Colombia""], ""B"": [""India"", ""A...",GPT,gpt-5.1-2025-11-13,2,487,11,0,none,NaN
117,q018,Bokmål,C,A,False,NaN,C,level 5,Er påstanden fakta eller mening?\nNye studier ...,"{""A"": [""Mening"", ""Fakta"", ""Fakta"", ""Mening""], ...",GPT,gpt-5.1-2025-11-13,2,1204,11,0,none,NaN
118,q019,Bokmål,C,A,False,NaN,C,level 3,Kan utsagnet sies å være hensikten med artikke...,"{""A"": [""Ja"", ""Ja"", ""Nei""], ""B"": [""Ja"", ""Nei"", ...",GPT,gpt-5.1-2025-11-13,2,714,11,0,none,NaN
125,q001,Bosnian,B,C,False,NaN,B,level 6,"Ako Tanja odluči da kupi automobil D, i prepro...","{""A"": ""1 575"", ""B"": ""8 925"", ""C"": ""9 000"", ""D""...",GPT,gpt-5.1-2025-11-13,2,182,11,0,none,NaN
126,q002,Bosnian,B,C,False,NaN,B,level 6,"Ako se ovakav trend prodaje nastavi, koje godi...","{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,116,11,0,none,NaN
128,q004,Bosnian,D,C,False,NaN,D,level 6,Kompanija koja iznajmljuje kamione potvrdila j...,"{""A"": ""U pravu je, jer je visina kutije srednj...",GPT,gpt-5.1-2025-11-13,2,434,11,0,none,NaN
134,q010,Bosnian,C,A,False,NaN,C,level 6,Razmotri dva perioda: od 2005. do 2010. godine...,"{""A"": [""India"", ""Kolumbija""], ""B"": [""India"", ""...",GPT,gpt-5.1-2025-11-13,2,528,11,0,none,NaN
142,q018,Bosnian,C,A,False,NaN,C,level 5,Da li tvrdnja predstavlja činjenicu ili mišlje...,"{""A"": [""Mišljenje"", ""Činjenica"", ""Činjenica"", ...",GPT,gpt-5.1-2025-11-13,2,1523,11,0,none,NaN
143,q019,Bosnian,B,A,False,NaN,B,level 3,Da li bi ova tvrdnja mogla predstavljati svrhu...,"{""A"": [""Da"", ""Da"", ""Ne""], ""B"": [""Da"", ""Ne"", ""N...",GPT,gpt-5.1-2025-11-13,2,932,11,0,none,NaN
150,q001,Bulgarian,B,C,False,NaN,B,level 6,Ако Таня реши да купи кола Г и я препродаде сл...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,174,11,0,none,NaN
153,q004,Bulgarian,D,C,False,NaN,D,level 6,"Фирмата, от която наели камиона, им обяснила, ...","{""A"": ""Тя е права, защото височината на средни...",GPT,gpt-5.1-2025-11-13,2,501,11,0,none,NaN
159,q010,Bulgarian,C,A,False,NaN,C,level 6,Разгледайте двата времеви периода: от 2005 до ...,"{""A"": [""Казахстан"", ""Колумбия""], ""B"": [""Казахс...",GPT,gpt-5.1-2025-11-13,2,540,11,0,none,NaN
161,q012,Bulgarian,D,B,False,NaN,D,level 5,За кое са единодушни Джаред Дайъмънд и учените...,"{""A"": ""Хората са се заселили на Великденския о...",GPT,gpt-5.1-2025-11-13,2,607,11,0,none,NaN
175,q001,Catalan,B,C,False,NaN,B,level 6,Si la Tània decideix comprar el cotxe D i reve...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,180,11,0,none,NaN
176,q002,Catalan,B,C,False,NaN,B,level 6,"Si aquesta tendència de vendes continua, en qu...","{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,114,11,0,none,NaN
184,q010,Catalan,C,A,False,NaN,C,level 6,Tingues en compte els dos períodes de temps: d...,"{""A"": [""Índia"", ""Colòmbia""], ""B"": [""Índia"", ""A...",GPT,gpt-5.1-2025-11-13,2,527,11,0,none,NaN
192,q018,Catalan,C,A,False,NaN,C,level 5,Aquesta afirmació és un fet o una opinió?\nEls...,"{""A"": [""Opinió"", ""Fet"", ""Fet"", ""Opinió""], ""B"":...",GPT,gpt-5.1-2025-11-13,2,1393,11,0,none,NaN
193,q019,Catalan,C,A,False,NaN,C,level 3,Aquesta afirmació podria representar l’objecti...,"{""A"": [""Sí"", ""Sí"", ""No""], ""B"": [""Sí"", ""No"", ""N...",GPT,gpt-5.1-2025-11-13,2,858,11,0,none,NaN
200,q001,Chinese,B,C,False,NaN,B,level 6,如果田妮决定购买汽车 D 并于三年后在良好车况下转售，那么这辆汽车的转售价格大约是多少 (z...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,138,11,0,none,NaN
201,q002,Chinese,B,C,False,NaN,B,level 6,如果此销售趋势持续下去的话，根据该模型，哪一年 DVD 销量会少于 1 百万张？,"{""A"": ""2015"", ""B"": ""2018"", ""C"": ""2020"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,106,11,0,none,NaN
203,q004,Chinese,D,C,False,NaN,D,level 6,出租货车的公司确认，货车 A 只能使用中号打包箱，才可以完全利用置物车厢的整个空间。\n马莎...,"{""A"": ""她的说法正确，因为中号打包箱的高度是大号打包箱高度的 2/3。"", ""B"": ...",GPT,gpt-5.1-2025-11-13,2,402,11,0,none,NaN
209,q010,Chinese,C,A,False,NaN,C,level 6,考虑两段时间：2005 年至 2010 年，以及 2010 年至 2015 年。\n就百分点...,"{""A"": [""印度"", ""哥伦比亚""], ""B"": [""印度"", ""亚美尼亚""], ""C""...",GPT,gpt-5.1-2025-11-13,2,508,11,0,none,NaN
212,q013,Chinese,C,D,False,NaN,C,level 4,里波和亨特举了哪些证据来支持他们对拉帕努伊岛上的大树消失的原因所提出的理论？,"{""A"": ""老鼠搭乘定居者的独木舟来到岛上。"", ""B"": ""老鼠可能是定居者刻意带来的。...",GPT,gpt-5.1-2025-11-13,2,477,11,0,none,NaN
214,q015,Chinese,C,A,False,NaN,C,level 5,此陈述是事实还是观点？\n作者在书中描述了几个文明社会因为做出了冲击环境的选择而崩溃。\n书...,"{""A"": [""事实"", ""观点"", ""事实"", ""事实"", ""观点""], ""B"": [""观...",GPT,gpt-5.1-2025-11-13,2,602,11,0,none,NaN
217,q018,Chinese,C,A,False,NaN,C,level 5,此陈述是事实还是观点？\n最近针对牛奶的健康效益的研究令人吃惊。\n研究显示喝牛奶会对健康产...,"{""A"": [""观点"", ""事实"", ""事实"", ""观点""], ""B"": [""事实"", ""事...",GPT,gpt-5.1-2025-11-13,2,1074,11,0,none,NaN
218,q019,Chinese,B,A,False,NaN,B,level 3,这项陈述能够代表此文的目的吗？\n质疑乳制品对一般健康的好处。\n讨论关于牛奶多方面的研究发...,"{""A"": [""是"", ""是"", ""否""], ""B"": [""是"", ""否"", ""否""], ""...",GPT,gpt-5.1-2025-11-13,2,629,11,0,none,NaN
225,q001,Croatian,B,C,False,NaN,B,level 6,Ako Tanja odluči kupiti automobil D i preproda...,"{""A"": ""1575"", ""B"": ""8925"", ""C"": ""9000"", ""D"": ""...",GPT,gpt-5.1-2025-11-13,2,174,11,0,none,NaN

In [75]:
df_summary = (
    df_false
    .groupby(['qid'])
    .size()
    .reset_index(name='num_incorrect')
)

print(df_summary)

     qid  num_incorrect
0   q001            172
1   q002            130
2   q003              4
3   q004             79
4   q007              7
5   q008             16
6   q010            162
7   q011              6
8   q012             13
9   q013              4
10  q014              4
11  q015             17
12  q018            140
13  q019            145
14  q023             14
15  q024              4